import {
    addDoc,
    collection,
    deleteDoc,
    doc,
    onSnapshot,
    setDoc,
    updateDoc,
} from "firebase/firestore";

import { APP_ID, db } from "@/lib/firebase";

import type { Unsubscribe } from "firebase/firestore";
import type { FlashCard, Lesson } from "../types/flashcard.types";

// ─── Firestore path helpers ────────────────────────────────────────────────

function lessonsCol(userId: string) {
    return collection(db, "artifacts", APP_ID, "users", userId, "lessons");
}

function lessonDoc(userId: string, lessonId: string) {
    return doc(db, "artifacts", APP_ID, "users", userId, "lessons", lessonId);
}

// ─── Subscribe ────────────────────────────────────────────────────────────

/**
 * Opens a real-time Firestore listener for the user's lesson list.
 * Returns an unsubscribe function — call it when the component unmounts.
 * Documents are sorted newest-first by createdAt.
 * The document ID becomes the authoritative `lesson.id`.
 */
export function subscribeLessons(
    userId: string,
    onUpdate: (lessons: Lesson[]) => void,
    onError: (err: Error) => void,
): Unsubscribe {
    return onSnapshot(
        lessonsCol(userId),
        (snap) => {
            const lessons = snap.docs
                .map((d) => ({ ...d.data(), id: d.id }) as Lesson)
                .sort((a, b) => b.createdAt - a.createdAt);
            onUpdate(lessons);
        },
        onError,
    );
}

// ─── Write operations ─────────────────────────────────────────────────────

/**
 * Creates a new lesson document. The document ID is auto-generated by
 * Firestore and returned — the caller does not need to supply one.
 */
export async function createLesson(userId: string, lesson: Omit<Lesson, "id">): Promise<string> {
    const ref = await addDoc(lessonsCol(userId), { ...lesson, userId });
    return ref.id;
}

/**
 * Overwrites a lesson document in place (replaces all top-level fields).
 * Expects `lesson.id` to be the Firestore document ID.
 */
export async function updateLesson(userId: string, lesson: Lesson): Promise<void> {
    const { id, ...data } = lesson;
    await setDoc(lessonDoc(userId, id), data, { merge: true });
}

/** Permanently deletes a lesson document. */
export async function deleteLesson(userId: string, lessonId: string): Promise<void> {
    await deleteDoc(lessonDoc(userId, lessonId));
}

/**
 * Updates correctCount / wrongCount for one card inside a lesson.
 * Receives the current `cards` array to avoid an extra read; the whole
 * array is written back because Firestore has no field-level array-item
 * update API for embedded objects.
 */
export async function recordCardResult(
    userId: string,
    lessonId: string,
    currentCards: FlashCard[],
    cardId: string,
    knew: boolean,
): Promise<void> {
    const updatedCards = currentCards.map((c) =>
        c.id !== cardId
            ? c
            : {
                  ...c,
                  correctCount: knew ? c.correctCount + 1 : c.correctCount,
                  wrongCount: !knew ? c.wrongCount + 1 : c.wrongCount,
              },
    );
    await updateDoc(lessonDoc(userId, lessonId), { cards: updatedCards });
}
